Add extra geometries view
Terralego/django-geostore pull request #33
Opened 2019-12-06 14:29 UTC by LePetitTim

2019-12-06 15:41 UTC, submarcos requested changes

2019-12-06 15:41 UTC, submarcos commented on geostore/views.py
> +            return Response(json.loads(serialize('geojson', extra_geometry, fields=('properties',),
serialize pas en geojson. utilise un serializer de FeatureExtraGeom. je suis en train de gerer les geojson a la demande dans un Renderer DRF

2019-12-09 16:53 UTC, submarcos commented on geostore/views.py
> +                extra_geometry = feature.extra_geometries.get(pk=id_extra_feature)
```suggestion
                extra_geometry = get_object_or_404(feature.extra_geometries.all(), pk=id_extra_feature)
```

2019-12-10 09:24 UTC, LePetitTim commented on geostore/views.py
> +            return Response(json.loads(serialize('geojson', extra_geometry, fields=('properties',),
Done

2019-12-10 09:24 UTC, LePetitTim commented on geostore/views.py
> +                extra_geometry = feature.extra_geometries.get(pk=id_extra_feature)
Done

2019-12-10 10:41 UTC, submarcos commented on geostore/views.py
> +    def extra_geometry(self, request, id_extra_feature=None, *args, **kwargs):
```suggestion
    def extra_geometry(self, request, id_extra_feature, *args, **kwargs):
```

2019-12-10 10:41 UTC, submarcos commented on geostore/views.py
> +                            status=status.HTTP_405_METHOD_NOT_ALLOWED)
dans le cas NOT allowed, mets  pas de data serialisée

2019-12-10 10:41 UTC, submarcos commented on geostore/views.py
> +            return Response(FeatureExtraGeomSerializer(extra_geometry).data,
```suggestion
            return Response(
```

2019-12-10 10:41 UTC, submarcos commented on geostore/views.py
> +        elif request.method == 'PUT' or request.method == 'PATCH':
```suggestion
        elif request.method in= ('PUT', 'PATCH'):
```

2019-12-10 10:41 UTC, submarcos commented on geostore/views.py
> +    def extra_layer_geometry(self, request, id_extra_layer=None, *args, **kwargs):
```suggestion
    def extra_layer_geometry(self, request, id_extra_layer, *args, **kwargs):
```

2019-12-10 10:41 UTC, submarcos commented on geostore/views.py
> +            return HttpResponseNotAllowed(permitted_methods=[],
? Response !

2019-12-10 17:08 UTC, submarcos commented on geostore/views.py
> +            return Response(status=status.HTTP_405_METHOD_NOT_ALLOWED)
je pense qu'on pourrait faire çà en 1er (pas editable -> out)

2019-12-10 17:10 UTC, submarcos requested changes

2019-12-10 17:10 UTC, submarcos commented on geostore/views.py
> +            url_path=r'extra_layer/(?P<id_extra_layer>\d+)', url_name='extra_layer_geometry')
```suggestion
            url_path=r'extra_layer/(?P<id_extra_layer>\d+)', url_name='create-extra-geometry')
```

2019-12-10 17:10 UTC, submarcos commented on geostore/views.py
> +            url_path=r'extra_geometry/(?P<id_extra_feature>\d+)', url_name='extra_geometry')
```suggestion
            url_path=r'extra_geometry/(?P<id_extra_feature>\d+)', url_name=update-extra-geometry')
```

2019-12-10 17:11 UTC, submarcos commented
inclure un changelog

2019-12-10 17:12 UTC, submarcos commented on geostore/views.py
>          serializer.save(layer_id=layer.pk)
```suggestion
        serializer.save(layer=layer)
```

2019-12-11 09:52 UTC, submarcos commented on geostore/views.py
> +    @action(detail=True, methods=['get', 'put', 'patch', 'delete'], permission_classes=[],
```suggestion
    @action(detail=True, methods=['get', 'put', 'patch', 'delete'],
```
permissions=[] -> ouvert aux 4 vents

2019-12-11 09:52 UTC, submarcos commented on geostore/views.py
> +    @action(detail=True, methods=['post'], permission_classes=[],
```suggestion
    @action(detail=True, methods=['post'],
```

2019-12-11 11:23 UTC, merged