Update routing
Terralego/django-geostore pull request #69
Opened 2020-10-08 15:46 UTC by LePetitTim

2020-10-09 14:38 UTC, submarcos commented on geostore/routing/helpers.py
> +
il faut factorise la requete exsiatnte et pas la récrire

2020-10-09 14:46 UTC, submarcos commented on geostore/routing/tests.py
> +            srid=app_settings.INTERNAL_GEOMETRY_SRID) for point in self.points]
c'est au niveau des points qu'il faut mettre le SRID mais au niveau de laligne (en dessous)

2020-10-09 14:46 UTC, submarcos commented on geostore/routing/tests.py
> +        geometry = LineString(*points)
```suggestion
        geometry = LineString(*points, srid=xxx)
```

2020-10-15 14:23 UTC, submarcos requested changes

2020-10-15 14:23 UTC, submarcos commented on geostore/routing/db/mixins.py
> +        super(UpdateRoutingMixin, self).clean(*args, **kwargs)
```suggestion
        super().clean(*args, **kwargs)
```

2020-10-15 14:23 UTC, submarcos commented on geostore/routing/helpers.py
> +
je preferai que la requete dwithin se fasse en amont, et qu'on apelle cette methode juste en lui passant la liste des ids des feature en parametre

2020-10-15 14:23 UTC, submarcos commented on geostore/routing/helpers.py
> +
update_topology(features_update=[1, 1000, 256]) ou un truc du genre

features_update = Feature.objects.filter(geom__dwithin(feat.geom, tolerance).values_list('pk', flat=True)

ou direct avec feat.layer.features.filter(xxx)

2020-10-15 14:23 UTC, submarcos commented on geostore/routing/helpers.py
> +
du coup pas la peine d'avoir feature ou create en parametres, juste une liste d'ids si on veut conditionner la requete à ces ids

2020-10-16 10:29 UTC, submarcos commented on geostore/routing/helpers.py
> +            features = layer.features.values_list('pk', flat=True)
dans ce cas autant pas faire de requete

2020-10-16 10:31 UTC, submarcos commented on geostore/routing/tasks.py
> +    if getattr(layer, 'routable', False):
routabe xiste toujours, pas la peine de faire un getattr

2020-10-16 10:31 UTC, submarcos commented on geostore/settings.py
> +GEOSTORE_TOLERANCE_ROUTING = getattr(settings, 'GEOSTORE_TOLERANCE_ROUTING', 0.000001)
il faut aussi utiliser cette valeur pour la valeur par defaut de la commande update_topology

2020-10-16 10:33 UTC, LePetitTim commented on geostore/routing/tasks.py
> +    if getattr(layer, 'routable', False):
pour le moment non ?

2020-10-16 10:33 UTC, LePetitTim commented on geostore/routing/helpers.py
> +            features = layer.features.values_list('pk', flat=True)
Tu veux dire quoi par la ?

2020-10-16 10:34 UTC, submarcos commented on geostore/routing/tasks.py
> +        features = type(feature).objects.filter(geom__dwithin=(feature.geom, tolerance)).values_list('pk', flat=True)
```suggestion
        features = layer.features.objects.filter(geom__dwithin=(feature.geom, tolerance)).values_list('pk', flat=True)
```

2020-10-16 10:35 UTC, submarcos commented on geostore/routing/helpers.py
> +            features = layer.features.values_list('pk', flat=True)
sans fonctionnait avec layer_id =, pas la peine de aire une requete pour mettre la liste des features du layer, si la couche contient 1million de donnée ca coute du temps pour rien

2020-10-16 10:39 UTC, submarcos requested changes

2020-10-16 10:39 UTC, submarcos commented on geostore/routing/tasks.py
> +    if getattr(layer, 'routable', False):
comment çà ? tu l'as bien mis dans une migration non ?

2020-10-16 10:45 UTC, submarcos commented on geostore/routing/helpers.py
> +            rows_where = f"""id IN {tuple(features)}"""
```suggestion
            rows_where = f"'layer_id={layer.pk} AND id IN {tuple(features)}"
```

2020-10-22 12:34 UTC, LePetitTim commented on geostore/routing/helpers.py
> +
C'est corrigé

2020-10-23 07:41 UTC, submarcos approved these changes

2020-10-23 07:41 UTC, merged