Add validation geom empty
Terralego/django-geostore pull request #74
Opened 2020-10-15 12:55 UTC by LePetitTim

2020-10-15 12:56 UTC, LePetitTim commented
https://github.com/Terralego/django-geostore/issues/49

2020-10-16 07:40 UTC, submarcos commented on geostore/tests/test_views/test_features.py
> +        response = self.client.put(self.detail_url, data={'geom': '{"type": "Point", "coordinates": []}',
this is not a polygon

2020-10-16 13:54 UTC, submarcos commented on geostore/serializers/__init__.py
> +    def to_internal_value(self, value):
don't override to_internal_value, just add custom validators on field

2020-10-22 09:39 UTC, submarcos requested changes
There is no entry in changelog

2020-10-22 09:39 UTC, submarcos commented on geostore/tiles/funcs.py
> +
put it in geostore.lookups.py

2020-10-23 07:37 UTC, submarcos approved these changes

2020-10-23 07:37 UTC, merged